### PR TITLE
Add 128bit numbers support

### LINKED ISSUE #82: Use native js `bigint` rather than `number`
Looks like 128-bit Clarity integers are being represented as js `number`'s (64-bit floating point). This causes problems with numbers that take ~53 or more bits to represent. I think the best solution here is to use native js `bigint` to represent these values. 

IMO, helper constructors like 
https://github.com/hirosystems/clarinet/blob/9beb61a538be055c220886300705eac552f6bf28/deno/index.ts#L318-L320
should continue to accept `number` as well as `bigint` (principal of being most permissive for inputs, but most explicit for outputs):
```ts
function uint(val: number | bigint) {
  return `u${val}`;
}
```

But response values (that represent 128-bit ints/uints) should return a `bigint`. That would result in this example code
https://github.com/hirosystems/clarinet/blob/9beb61a538be055c220886300705eac552f6bf28/examples/billboard/tests/billboard_test.ts#L34-L35
becoming
```ts
        assetMaps = chain.getAssetsMaps();
        assertEquals(assetMaps.assets['STX'][wallet_1.address], balance - 210n);
```

Obviously this isn't much of a concern with something like a STX balance that is unlikely to be higher than a 53-bit integer, but FTs and many other use cases use larger numbers where this becomes an issue.

### PR DESCRIPTION
**Pull request by LNow**
This PR adds 128bit numbers support.

Close #82

### CODE REVIEW

**Review by lgalabru — APPROVED** [review]
Thank you for this contribution @LNow, LGTM!

**Comment by lgalabru** [comment]
@CharlieC3 what would be the next steps, concerning the windows build error?

Screen Shot 2021-11-02 at 12 26 37 PM

**Comment by CharlieC3** [comment]
@lgalabru The build is failing because a GH secret is required, and the PR is from a fork which isn't allowed to use GH secrets. Unfortunately there is no way around this besides re-opening the PR from an internal branch or skipping the step (and others) entirely.

**Comment by lgalabru** [comment]
Oh ok that's fine then, I thought that we were looking at an expired certificate or something.
Thanks!

**Pull request merged**
